# Use 4.16 as the base
# 4.6.11 release image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:31feb7503f06db4023350e3d9bb3cfda661cc81ff21cef429770fb12ae878636

ARG OCP_RELEASE_IMAGE

FROM $OCP_RELEASE_IMAGE

ARG KATA_RELEASE_VERSION=3.9.0

COPY snp/centos-snp.repo /etc/yum.repos.d

WORKDIR /

# Install upstream Kata bits
RUN curl -LO https://github.com/niteeshkd/ocp-snp-coco/raw/refs/heads/main/data/ocp_kata-static-${KATA_RELEASE_VERSION}-amd64.tar.xz && \ 
    mkdir -p /var/opt && \
    tar xvf ocp_kata-static-${KATA_RELEASE_VERSION}-amd64.tar.xz --strip-components=2 -C /opt && \
    mv /opt/kata /usr/kata && \
    echo 'd /var/opt 755 root root -' >> /usr/lib/tmpfiles.d/kata.conf && \
    echo 'L+ /opt/kata - - - - /usr/kata' >> /usr/lib/tmpfiles.d/kata.conf


COPY snp/crio.conf.d/ /etc/crio/crio.conf.d/

# Copy the config toml to a read-write mount-point so that this can be overriden via 
# machineconfig
RUN mkdir -p /etc/kata-containers/snp/ && \
    cp /usr/kata/share/defaults/kata-containers/configuration-qemu-snp.toml /etc/kata-containers/snp/configuration-qemu-snp.toml

# Install RHEL9.5 beta kernel with SEV-SNP support
RUN rpm-ostree override replace https://people.redhat.com/~bdas/rhel-9/kernel-{,core-,modules-,modules-core-,modules-extra-}5.14.0-503.12.1_att_fix_test.el9_5.x86_64.rpm
 
# Install qemu related packages from centos repo
RUN rpm-ostree install qemu-kvm qemu-img

RUN rpm-ostree cleanup -m && \
    ostree container commit
