# Use 4.16 as the base
# 4.6.11 release image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:31feb7503f06db4023350e3d9bb3cfda661cc81ff21cef429770fb12ae878636

ARG OCP_RELEASE_IMAGE

FROM $OCP_RELEASE_IMAGE

ARG KATA_RELEASE_VERSION=3.9.0

COPY snp/centos-snp.repo /etc/yum.repos.d

WORKDIR /

# Install upstream Kata bits
RUN curl -LO https://github.com/kata-containers/kata-containers/releases/download/${KATA_RELEASE_VERSION}/kata-static-${KATA_RELEASE_VERSION}-amd64.tar.xz && \
    mkdir -p /var/opt && \
    tar xvf  kata-static-${KATA_RELEASE_VERSION}-amd64.tar.xz --strip-components=2 -C /opt && \
    mv /opt/kata /usr/kata && \
    echo 'd /var/opt 755 root root -' >> /usr/lib/tmpfiles.d/kata.conf && \
    echo 'L+ /opt/kata - - - - /usr/kata' >> /usr/lib/tmpfiles.d/kata.conf


COPY snp/crio.conf.d/ /etc/crio/crio.conf.d/

#Install CentOS stream kernel
RUN rpm-ostree override replace https://mirror.stream.centos.org/SIGs/9-stream/virt/x86_64/tdx-devel/Packages/k/kernel-{,core-,modules-,modules-core-,modules-extra-}5.14.0-480.el9s.x86_64.rpm
 

RUN rpm-ostree cleanup -m && \
    ostree container commit
