# Use 4.18 as the base
# 4.18.4 release image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:5d914162d9b4fc00aea081d0e31ae348b1f7b2222011200dfbfdff0d54b1dbe4

ARG OCP_RELEASE_IMAGE

FROM $OCP_RELEASE_IMAGE

COPY snp/centos-snp.repo /etc/yum.repos.d

WORKDIR /

# Replace the existing kernel
COPY snp/rpms/ /
RUN rpm-ostree override replace kernel-{,core-,modules-,modules-core-,modules-extra-}5.14.0-570.4.1.el9_6.x86_64.rpm
 
# Install qemu
RUN rpm-ostree override replace https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/numactl-libs-2.0.19-1.el9.x86_64.rpm
RUN rpm-ostree install qemu-kvm 

# Install Kata-containers rpm
RUN rpm-ostree override replace https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/glibc-{,common-,gconv-extra-,minimal-langpack-}2.34-180.el9.x86_64.rpm
RUN rpm-ostree override replace https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/libgcc-11.5.0-5.el9.x86_64.rpm
RUN rpm-ostree override replace https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/elfutils-{libelf-,libs-}0.192-5.el9.x86_64.rpm

RUN rpm-ostree install kata-containers-3.14.0-1.rhaos4.19.el9.x86_64.rpm 

# Selinux adjustments to provide access to sev
RUN setsebool -P container_use_devices 1

RUN rpm-ostree cleanup -m && \
    ostree container commit
